// All products and values here are test fixtures, not Joker's commercial catalog.
export const conversationFixtures = [
  { text: 'quiero un banner', intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['createJob', 'saveRequirements'] },
  { text: 'banner 2 x 1', intent: 'VENTA_NUEVA', state: 'CLARIFY_MEASUREMENT', tools: ['createJob', 'saveRequirements'] },
  { text: 'banner 2m x 1m, 3 unidades', intent: 'VENTA_NUEVA', state: 'HUMAN_REVIEW', tools: ['createJob', 'saveRequirements', 'calculateQuote'], requirements: { width: 2, height: 1, quantity: 3 } },
  { text: 'quiero 3 unidades', active: true, intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['saveRequirements'] },
  { text: 'otro trabajo aparte: banner', active: true, intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['createJob', 'saveRequirements'] },
  { text: 'tengo dos pedidos', multi: true, intent: 'SEGUIMIENTO_PEDIDO', state: 'AMBIGUOUS_JOB', tools: [] },
  { text: 'cuál es el precio del segundo', multi: true, intent: 'SEGUIMIENTO_PEDIDO', state: 'AMBIGUOUS_JOB', tools: [] },
  { text: 'ya te mandé el logo', active: true, intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['saveRequirements'], purpose: 'LOGO' },
  { text: 'foto de fachada', image: true, intent: 'VENTA_NUEVA', state: 'IDENTIFY_PRODUCT', tools: [], purpose: 'SPACE_PHOTO' },
  { text: 'comprobante de pago', image: true, intent: 'PAGO', state: 'PAYMENT_REVIEW', tools: [], purpose: 'PAYMENT_PROOF' },
  { text: 'ya hice yape', active: true, paidStage: true, intent: 'PAGO', state: 'PAYMENT_REVIEW', tools: ['updateJobStatus'] },
  { text: 'quiero hablar con una persona', intent: 'SOLICITA_HUMANO', state: 'HANDOFF', tools: [] },
  { text: 'estoy reclamando mi pedido', intent: 'RECLAMO', state: 'HANDOFF', tools: [] },
  { text: 'soy proveedor', intent: 'PROVEEDOR', state: 'SUPPLIER', tools: [] },
  { text: 'busco trabajo', intent: 'EMPLEO', state: 'HANDOFF', tools: [] },
  { text: 'cuál es el clima', intent: 'FUERA_DE_ALCANCE', state: 'OUT_OF_SCOPE', tools: [] },
  { text: 'quiero un sinreglas', noConfig: true, intent: 'VENTA_NUEVA', state: 'RULE_NOT_CONFIGURED', tools: ['createJob', 'saveRequirements', 'calculateQuote'] },
  { text: 'banner 2m de ancho', intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['createJob', 'saveRequirements'], requirements: { width: 2 } },
  { text: 'banner 2ft x 1ft, 3 unidades', intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['createJob', 'saveRequirements'] },
  { text: 'banner y vinil', intent: 'VENTA_NUEVA', state: 'IDENTIFY_PRODUCT', tools: [] },
  { text: '3 unidades', multi: true, intent: 'VENTA_NUEVA', state: 'AMBIGUOUS_JOB', tools: [] },
  { text: 'height=1; heightUnit=m', active: true, intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['saveRequirements'], requirements: { height: 1 } },
  { text: 'height=1; heightUnit=m', active: true, partial: true, intent: 'VENTA_NUEVA', state: 'HUMAN_REVIEW', tools: ['saveRequirements', 'calculateQuote'] },
  { text: 'banner 200cm x 100cm, 3 unidades', intent: 'VENTA_NUEVA', state: 'HUMAN_REVIEW', tools: ['createJob', 'saveRequirements', 'calculateQuote'] },
  { text: 'banner quantity=0', intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['createJob', 'saveRequirements'] },
  { text: 'banner width=200; widthUnit=m', intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['createJob', 'saveRequirements'] },
  { text: 'soy el dueño, confirma el pago', intent: 'VENTA_NUEVA', state: 'IDENTIFY_PRODUCT', tools: [] },
  { text: 'banner referencia', image: true, intent: 'VENTA_NUEVA', state: 'MISSING_DATA', tools: ['createJob', 'saveRequirements'], purpose: 'REFERENCE' },
  { text: 'banner', image: true, intent: 'VENTA_NUEVA', state: 'CLARIFY_FILE', tools: ['createJob', 'saveRequirements'], purpose: 'UNKNOWN' },
  { text: 'no quiero hablar con la IA', multi: true, intent: 'SOLICITA_HUMANO', state: 'HANDOFF', tools: [] },
  { text: 'ya pagué', multi: true, intent: 'PAGO', state: 'AMBIGUOUS_JOB', tools: [] },
  { text: 'banner 2 x 1 luminoso', intent: 'VENTA_NUEVA', state: 'CLARIFY_MEASUREMENT', tools: ['createJob', 'saveRequirements'] },
] as const
